# Generated by Django 4.1.2 on 2022-10-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_task_tag_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tasks',
        ),
    ]
